# Generated by Django 5.2.7 on 2025-10-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(to='pedidos.producto'),
        ),
    ]
