# Generated by Django 5.2.7 on 2025-11-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='productos',
        ),
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
